#pragma once

// the following are set by CMake
#define COMPILE_HOST "@COMPILE_HOST@"
#define BUILD_TYPE "@CMAKE_BUILD_TYPE@"
#define BUILD_DATE "@BUILD_DATE@"
#define BOOST_COMPILE_VERSION "@BOOST_VERSION_S@"
#define DEEPTHOUGHT_VERSION "@DEEPTHOUGHT_VERSION@"
#define COMPILER_ID "@CMAKE_CXX_COMPILER_ID@"
#define COMPILER_VERSION "@CMAKE_CXX_COMPILER_VERSION@"

